const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const w={console,localStorage:{m:new Map(),getItem(k){return this.m.get(k)||null},setItem(k,v){this.m.set(k,String(v))},removeItem(k){this.m.delete(k)}},addEventListener(){}};w.window=w;const c=vm.createContext(w);for(const f of ['wallets/walletStore.js','wallets/walletTypes.js','wallets/walletLedger.js','wallets/walletCaixa.js','wallets/walletManager.js','defi/js/data.js','defi/js/pool-history.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});const a=w.AtlasWallets.all()[0];w.AtlasCaixa.registrar({tipo:'deposito',walletId:a.id,ativo:'USDT',qtd:1000,valorUSD:1000});return {w,a,H:w.DeFiPoolHistorico,S:w.DeFiStore};}
test('relatório discrimina aportes, reinvestimento, retirada, taxas e caixa sem dupla contagem',()=>{const {w,a,H,S}=setup();const p=S.addPool({walletId:a.id,base:'SOL',quote:'HYPE',protocol:'Orca',chain:'Solana',capital:100,currentValue:100,qtyBase:0.02,qtyQuote:4,fees:[]});S.addEvent(p.id,{type:'aporte',amountUSD:20});S.addFee(p.id,{amount:5,status:'coletada'});S.addEvent(p.id,{type:'reinvest',amountUSD:2});S.addEvent(p.id,{type:'retirada',amountUSD:10});S.addFee(p.id,{amount:3,status:'pendente'});S.updatePool(p.id,{currentValue:115,qtyBaseNow:0,qtyQuoteNow:6});S.closePool(p.id);const h=H.registro(S.closed()[0]);assert.equal(h.capitalInicial,100);assert.equal(h.aportesAdicionais,20);assert.equal(h.resumo.aportado,120);assert.equal(h.resumo.reinvestido,2);assert.equal(h.resumo.retirado,10);assert.equal(h.resumo.resultado,11);assert.equal(h.resumo.varAtivos,3);assert.equal(h.resumo.taxasTotal,8);assert.equal(h.retornoFechamento,118);assert.equal(h.caixa.entradas,133);assert.equal(h.caixa.saidas,122);assert.equal(h.caixa.liquido,11);assert.equal(h.tokens[0].entrada,0.02);assert.equal(h.tokens[0].ultima,0);assert.equal(h.tokens[1].ultima,6);assert.equal(h.encerrada,true);});
test('quantidade de entrada não é inventada como quantidade final; registros antigos incompletos não viram lucro zero',()=>{const {H}=setup();const h=H.registro({id:'antiga',base:'SOL',quote:'HYPE',capital:100,qtyBase:1,qtyQuote:5,currentValue:999,closedAt:'2026-01-02',profit:999});assert.equal(h.resumo,null);assert.equal(h.tokens[0].ultima,null);assert.equal(h.tokens[0].entrada,1);assert.equal(h.caixa.liquido,null);assert.equal(h.retornoFechamento,null);});
test('fotografia do fechamento prevalece sobre campos derivados alterados e não é recalculada',()=>{const {H}=setup();const p={id:'p',base:'SOL',quote:'HYPE',capital:100,currentValue:999,closedAt:'2026-01-02',finalValue:104,profit:999,closeSummary:{aportado:100,resultado:4,taxasTotal:0,varAtivos:4}};const before=JSON.stringify(p);const h=H.registro(p);assert.equal(h.resumo.resultado,4);assert.equal(h.retornoFechamento,104);assert.equal(JSON.stringify(p),before);});
test('lista de ciclos respeita carteira proprietária e inclui encerradas de outra carteira',()=>{const {w,a,S}=setup();const b=w.AtlasWallets.create({name:'M2P',type:'global'});w.AtlasCaixa.registrar({tipo:'deposito',walletId:b.id,valorUSD:100});const p=S.addPool({walletId:b.id,base:'SOL',quote:'HYPE',capital:100,currentValue:100});S.closePool(p.id);assert.equal(S.closedDeTodasCarteiras().length,1);assert.equal(S.closedDeTodasCarteiras()[0].walletId,b.id);});
test('HTML escapa textos de carteira, protocolo e notas',()=>{const {H}=setup();const html=H.card({id:'x',base:'<img src=x onerror=x>',quote:'SOL',protocol:'<script>x</script>',closedAt:'2026-01-01',reason:'<b>x</b>'},'<svg onload=x>');assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<svg onload'));assert.ok(html.includes('&lt;'));});
test('data sintética do store não vira data histórica comprovada',()=>{const {H}=setup();const h=H.registro({id:'antiga',base:'SOL',quote:'HYPE',capital:100,closedAt:'2026-01-02'});assert.equal(h.eventos[0].date,null);assert.equal(h.eventos[0].derivado,true);assert.equal(h.aberturaEm,null);assert.equal(h.aportesAdicionais,null);const html=H.card({id:'antiga',base:'SOL',quote:'HYPE',capital:100,closedAt:'2026-01-02'});assert.ok(html.includes('derivado do cadastro'));});
test('ciclo com perda preserva resultado negativo e centavos no caixa',()=>{const {w,a,H,S}=setup();const p=S.addPool({walletId:a.id,base:'SOL',quote:'HYPE',capital:100,currentValue:96.12,fees:[]});S.closePool(p.id);const h=H.registro(S.closed()[0]);assert.ok(Math.abs(h.resumo.resultado+3.88)<1e-9);assert.ok(Math.abs(h.caixa.liquido+3.88)<1e-9);assert.equal(h.retornoFechamento,96.12);assert.ok(H.card(S.closed()[0]).includes('96,12'));});
